const assets = [
	{
	"id":"Assets_Audio_dashSimple",
	"url":"assets/audio\\Assets_Audio_dashSimple.mp3"
	},
	{
	"id":"Cartoon-Mouth-Sound-01",
	"url":"assets/audio\\Cartoon-Mouth-Sound-01.mp3"
	},
	{
	"id":"Cartoon-Mouth-Sound-02",
	"url":"assets/audio\\Cartoon-Mouth-Sound-02.mp3"
	},
	{
	"id":"Cartoon-Mouth-Sound-06",
	"url":"assets/audio\\Cartoon-Mouth-Sound-06.mp3"
	},
	{
	"id":"Cartoon-Mouth-Sound-13",
	"url":"assets/audio\\Cartoon-Mouth-Sound-13.mp3"
	},
	{
	"id":"Cartoon-Mouth-Sound-18",
	"url":"assets/audio\\Cartoon-Mouth-Sound-18.mp3"
	},
	{
	"id":"Cartoon-Mouth-Sound-20",
	"url":"assets/audio\\Cartoon-Mouth-Sound-20.mp3"
	},
	{
	"id":"coins_04",
	"url":"assets/audio\\coins_04.mp3"
	},
	{
	"id":"dropTile",
	"url":"assets/audio\\dropTile.mp3"
	},
	{
	"id":"Fire-Burst-Small-01",
	"url":"assets/audio\\Fire-Burst-Small-01.mp3"
	},
	{
	"id":"getCrazyOne",
	"url":"assets/audio\\getCrazyOne.mp3"
	},
	{
	"id":"getstar",
	"url":"assets/audio\\getstar.mp3"
	},
	{
	"id":"getThemAll",
	"url":"assets/audio\\getThemAll.mp3"
	},
	{
	"id":"Harp-Flutter-02",
	"url":"assets/audio\\Harp-Flutter-02.mp3"
	},
	{
	"id":"HolidayWeasel",
	"url":"assets/audio\\HolidayWeasel.mp3"
	},
	{
	"id":"item",
	"url":"assets/audio\\item.mp3"
	},
	{
	"id":"kill",
	"url":"assets/audio\\kill.mp3"
	},
	{
	"id":"magic",
	"url":"assets/audio\\magic.mp3"
	},
	{
	"id":"Musical-Beep-Loop-02",
	"url":"assets/audio\\Musical-Beep-Loop-02.mp3"
	},
	{
	"id":"Ping-Slide-Down",
	"url":"assets/audio\\Ping-Slide-Down.mp3"
	},
	{
	"id":"place",
	"url":"assets/audio\\place.mp3"
	},
	{
	"id":"place2",
	"url":"assets/audio\\place2.mp3"
	},
	{
	"id":"Pop-Low-Pitch-Up-02",
	"url":"assets/audio\\Pop-Low-Pitch-Up-02.mp3"
	},
	{
	"id":"Pop-Musical",
	"url":"assets/audio\\Pop-Musical.mp3"
	},
	{
	"id":"place3",
	"url":"assets/audio\\place3.mp3"
	},
	{
	"id":"Pop-Tone",
	"url":"assets/audio\\Pop-Tone.mp3"
	},
	{
	"id":"pop",
	"url":"assets/audio\\pop.mp3"
	},
	{
	"id":"shoosh",
	"url":"assets/audio\\shoosh.mp3"
	},
	{
	"id":"pop2",
	"url":"assets/audio\\pop2.mp3"
	},
	{
	"id":"SneakySnitch",
	"url":"assets/audio\\SneakySnitch.mp3"
	},
	{
	"id":"Synth-Appear-01",
	"url":"assets/audio\\Synth-Appear-01.mp3"
	},
	{
	"id":"Tap-01",
	"url":"assets/audio\\Tap-01.mp3"
	},
	{
	"id":"teleport",
	"url":"assets/audio\\teleport.mp3"
	},
	{
	"id":"TheBuilder",
	"url":"assets/audio\\TheBuilder.mp3"
	},
	{
	"id":"Whoosh",
	"url":"assets/audio\\Whoosh.mp3"
	}
];

export default assets;
